name: Test Publish Vocabulary Workflow

on:
    pull_request:
    release:
        types: [published]


jobs:
    test-workflow:
        if: github.repository != 'eu-parc/vocabulary-template'
        uses: eu-parc/voc2skosmos-workflows/.github/workflows/csv2skos.yml@main
        with:
            namespace: http://www.placeholder.com/
            namespace_label: placeholder